dataset_name: 'DMR Classification Gray'
dataset_path: '$CUTS_ROOT/data/DMR/'
model_save_path: 'dmr_runs_classification_gray/checkpoints/dmr_run.pty'
output_save_path: 'dmr_runs_classification_gray/results/'
log_folder: 'dmr_runs_classification_gray/logs'
model_setting: 'full' # 'full', 'no_recon', 'no_contrastive'
learning_rate: 1e-3
weight_decay: 1e-4
max_epochs: 70
patience: 10
batch_size: 16
num_kernels: 16
sampled_patches_per_image: 16 # recommend: 4 or above.
num_workers: 8
lambda_contrastive_loss: 0.01  # Between 0 and 1. no_recon == 1. no_contrastive == 0.
random_seed: 2021
train_val_ratio: '8:2'
is_binary: True
no_label: True